##################################################
{ pkgs
, haskellUtilities

, strip
}:

##################################################
theDynamicDerivation:

# ^ the derivation of a package generated by « cabal2nix »'s, or any package which looks like:
# « haskellPackages.callPackage ({mkDerivation, base, ...}: mkDerivation { ... }) {} ».

##################################################
let

inherit (pkgs) lib;

#------------------------------------------------#


in
##################################################
let

static = {

  gmp = pkgs.gmp6.override { withStatic = true; };

  zlib = pkgs.zlib.static;

};

#------------------------------------------------#

configureFlags-forStaticLinking = [

          "--ghc-option=-optl=-static"

          "--extra-lib-dirs=${static.gmp}/lib"
          "--extra-lib-dirs=${static.zlib}/lib"

        ] ++ pkgs.lib.optionals (!strip) [

          "--disable-executable-stripping"

        ];

in
##################################################
let

override-forStaticLinking = attrs:

  {
    configureFlags = attrs.configureFlags ++ configureFlags-forStaticLinking;

    isLibrary    = true;
    isExecutable = true;

    enableSharedExecutables = false;
    enableSharedLibraries   = false;

  #      isLibrary    = true;
  #      configureFlags = configureFlags;
  };

#------------------------------------------------#

theStaticDerivation =

  haskellUtilities.overrideCabal theDynamicDerivation override-forStaticLinking;

#------------------------------------------------#

in
##################################################

theStaticDerivation

##################################################