resolver: lts-8.12
compiler: ghc-8.0.2

nix:
   # enable: true  
   # on NixOS (and/or Linux/OSX), you global stack.yaml can enable `nix`. otherwise, it's disabled. 
  pure: true
  packages: []

packages:
- .

extra-deps: []
