resolver: nightly-2017-12-09
# compiler: ghc-8.2.2

nix:
  enable: false
  pure: true
  packages: []

packages:
- .

extra-deps: []

# build:
#   library-profiling: true 
#   executable-profiling: true 
#   haddock: true 
#   haddock-arguments:
#     haddock-args:
#     - --hyperlink-source 
